name: Deploy to Server
on:
  push:
    branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /home/ticket-api.masters-ts.com/Ticket_Backend/
            git checkout -f && git pull origin main
            rm -rf node_modules/.cache 
            npm install
            npm run build || true
